/*
-- Query: SELECT * FROM va_por_mi_cuenta.padrinos
where num_empleado like "vips%"
LIMIT 0, 1000

-- Date: 2014-08-14 01:52
*/
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1356,'vips6398137','ILEANA ARACELI FELIX DIAZ SIERRA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1357,'vips6000317','GUADALUPE FERNANDO CERVANTES MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1358,'vips521430','MARIA GUADALUPE ESCAMILLA ANGELES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1359,'vips6407825','LUIS FERNANDO GONZALEZ VAZQUEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1360,'vips6521106','DANIEL SEBASTIAN SOLORZANO DUENAS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1361,'vips5570967','BRENDA KARINA HERNANDEZ FLORES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1362,'vips6104078','ANA LUZ PUIG MONARRES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1363,'vips577348','GERARDO CESAR DELGADO REYES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1364,'vips1150352','MARIBEL PATRICIA SANTIAGO ROJAS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1365,'vips5280822','LUBIN ROMERO URIOSTEGUI','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1366,'vips6002342','CLAUDIA FLORES COZART','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1367,'vips6080720','GIL ALBERTO OLIVARES MEDINA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1368,'vips5178504','CLAUDIA ISELA PAZ VALDEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1369,'vips6828829','PEDRO GUTIERREZ DAVALOS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1370,'vips2482752','LYDIA ESPERANZA TORRES GARCIA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1371,'vips1147174','MARIA GUADALUPE MEJIA HERNANDEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1372,'vips5035023','MARIA CONCEPCION VERA JUAREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1373,'vips6250140','CARLOS ALFONSO VERGARA PARRA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1374,'vips5506612','JOSE JAVIER MENESES SOBRINO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1387,'vips6554955','GISELA AIDE CASTILLO DOMINGUEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1388,'vips6007396','LETICIA CORENO GARCIA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1389,'vips6554933','FRANCISCO GONZALEZ REZA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1390,'vips5645930','ARTURO CORTES SERRANO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1391,'vips5131233','FRANCISCO CURA TRUJILLO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1392,'vips1143706','ROBERTO MIGUEL SANTILLAN SANCHEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1393,'vips6445873','EMMA HERNANDEZ GARCIA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1394,'vips6379565','LILIANA MILLAN GONZALEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1395,'vips6419672','ELISA CRISTINA OLIVARES RAMOS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1396,'vips6327500','JOSE LUIS CARDENAS VERA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1397,'vips6630115','JUAN CARLOS LOPEZ MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1398,'vips5106091','FERNANDO GONZALEZ RUBIO GUTIERREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1399,'vips6003449','MONICA LILIANA SANDOVAL PRADO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1400,'vips5407922','BERNARDO CASTRO NEGRETE','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1401,'vips559138','OLGA REGINA VAZQUEZ LOPEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1402,'vips6388249','ROCIO ARACELI ALONSO MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1403,'vips6746813','CLAUDIA ADRIANA GASCON GARCIA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1404,'vips6649288','ZUE ADRIANA ORTEGA JIMENEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1405,'vips6672438','NOEMI RAMIREZ QUINTERO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1406,'vips6919327','SERGIO CANO FLORES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1407,'vips2584455','JOSE ANGEL LOPEZ CASTILLO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1408,'vips6247241','GRISELDA BELLO ESQUIVEL','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1409,'vips6390088','LISSETE FABIOLA MALDONADO GALINDO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1410,'vips6004752','EDUARDO GONZALEZ GARCIA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1411,'vips6026532','MARIA MAGDALENA SOLIS SUAREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1412,'vips6401689','CARLOS FRANCISCO ESCOTO RODRIGUEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1413,'vips6737633','ANDREA AGLAE PILIADO RODRIGUEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1414,'vips6003970','ADRIAN JOSUE URBINA GALVAN','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1415,'vips6598812','MELANNIE GEOVANNA VILLAGOMEZ CRUZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1416,'vipsVendor','CARLOS ORLANDO GONZALEZ PEREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1417,'vipsVendor','FERNANDO LIRA MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1418,'vips5553310','ADRIANA GABRIELA LEGORRETA MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1419,'vips6897499','EDUARDO HERRERA PEREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1420,'vips6589357','JORGE ISAAC CASTRO PEREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1421,'vips6781653','JOSE ALBERTO MENDOZA CHAVEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1422,'vips6788581','MANUEL OMAR MERA FLORES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1423,'vips6036665','AMALIA AGUILA FRANCO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1424,'vips6562134','EDUARDO GABRIEL CARDENAS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1425,'vips6002343','ALEJANDRA MONDRAGON CHAVARRIA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1426,'vips1177070','LUIS VILLASANA LARIOS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1427,'vips6257964','ERICK IVAN ORTEGA GONZALEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1428,'vips6000210','ALBERTO VALLEJO PERALTA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1429,'vips6000282','FAUSTO JUAREZ MONTES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1430,'vips1119976','ANA LAURA OLIVA DURAN','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1431,'vips1141144','MARTIN ALCANTARA CAZARES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1432,'vips1086736','JUAN MONTANO SIERRA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1433,'vips6004684','MIGUEL ANGEL ARZATE SOSA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1434,'vips2773230','MARIBEL GAMEZ MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1435,'vips5367364','JULISSA GARCIA RUIZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1436,'vips1169555','CARLOS HERNANDEZ GUTIERREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1437,'vips6577884','VERONICA MATIAS TORRES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1438,'vips6194300','CECILIA MENDOZA BAUTISTA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1439,'vips2115296','GILBERTO ALEJANDRO RAMIREZ GRANADOS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1440,'vips5637204','MIGUEL ANGEL SUAREZ HERNANDEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1441,'vips6004918','LUIS ROBERTO VILLEGAS MARTINEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1442,'vips6037148','MIGUEL ANGEL CASTRO NOVELO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1443,'vips6120679','ADRIANA ALCANTARA SOMERA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1444,'vips6766011','ALEJANDRO VARGAS FIGUEROA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1445,'vips6603344','CHRISTIAN ALEJANDRO ALVARADO CANALES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1446,'vips6102052','REYNA GUADALUPE AYALA FUENTES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1447,'vips6189502','MARIA ASUNCION REBOLLAR BENITEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1448,'vips5449167','ILEANA MONTEMAYOR MENCHACA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1449,'vips6777189','ALEJANDRO CORONEL RIVAS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1450,'vips6890843','ORLANDA CALDERON ORTIZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1451,'vips6097177','CLAUDIA EVELYN PEREZ MORALES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1452,'vips5044719','ALMA DELIA LOPEZ GONZALEZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1453,'vips1100843','OTILIA OCAMPO SANDOVAL','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1454,'vips1967116','JESUS ENRIQUE REYNOSO ALVAREZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1455,'vips6306599','GRACIELA CABALLERO REYES','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1456,'vips1973114','ARELI HERNANDEZ CAMPOS','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1457,'vips6433176','SANDY AIDEE LOPEZ ESCAMILLA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1458,'vips1602911','VERONICA SANCHEZ ROA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1459,'vips3289778','MARIA ELBA CHAVEZ ORTIZ','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1460,'vips6413830','TANIA PAOLA FLORES PEDRAZA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1461,'vips6756759','LUZ DEL CARMEN DIAZ DE VIVAR LUNA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1462,'vips376534','RAUL ROSETE GUADARRAMA','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1463,'vips1025321','JOSE ANTONIO ALVARADO CALVO','',0);
INSERT INTO `padrinos` (`idpadrinos`,`num_empleado`,`nombre`,`correo`,`padrino`) VALUES (1464,'vips5532774','VICTOR ENRIQUE GUZMAN MARTINEZ','',0);
